### ISSUE TITLE
[BUG] Crash on iOS when using MediaElement inside a CarouselView

### ISSUE THREAD

**Issue by dan3988** [CommunityToolkit/Maui#1721]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

When using a MediaElement inside a carousel view, the app will crash on iOS with the following message:
```
child view controller:<AVPlayerViewController: 0x104008800> should have parent view controller:<Microsoft_Maui_Controls_Handlers_Items_CarouselViewController: 0x102777b80> but actual parent is:<Microsoft_Maui_Platform_PageViewController: 0x102774910>
```

Full stack trace:
```
Unhandled Exception:
ObjCRuntime.ObjCException: Objective-C exception thrown.  Name: UIViewControllerHierarchyInconsistency Reason: child view controller:<AVPlayerViewController: 0x104008800> should have parent view controller:<Microsoft_Maui_Controls_Handlers_Items_CarouselViewController: 0x102777b80> but actual parent is:<Microsoft_Maui_Platform_PageViewController: 0x102774910>
Native stack trace:
	0   CoreFoundation                      0x0000000180491128 __exceptionPreprocess + 172
	1   libobjc.A.dylib                     0x000000018008412c objc_exception_throw + 56
	2   CoreFoundation                      0x0000000180491038 -[NSException initWithCoder:] + 0
	3   UIKitCore                           0x00000001857f3ae4 -[UIView(Hierarchy) _associatedViewControllerForwardsAppearanceCallbacks:performHierarchyCheck:isRoot:] + 216
	4   UIKitCore                           0x00000001857f4250 -[UIView(Hierarchy) _willMoveToWindow:withAncestorView:] + 184
	5   UIKitCore                           0x00000001857f4d18 _makeSubTreePerformSelector + 428
	6   UIKitCore                           0x00000001857f4d54 _makeSubTreePerformSelector + 488
	7   UIKitCore                           0x00000001857f4d54 _makeSubTreePerformSelector + 488
	8   UIKitCore                           0x00000001858016a0 -[UIView(Internal) _addSubview:positioned:relativeTo:] + 384
	9   UIKitCore                           0x0000000184a39e3c -[UICollectionView _addSubview:positioned:relativeTo:] + 144
	10  UIKitCore                           0x00000001854bc098 -[_UICollectionViewSubviewRouter addControlledSubview:zIndex:orderMode:] + 816
	11  UIKitCore                           0x0000000184a39a34 -[UICollectionView _addControlledSubview:atZIndex:forced:initialAttributes:] + 300
	12  UIKitCore                           0x0000000184a3e038 -[UICollectionView _createPreparedCellForItemAtIndexPath:withLayoutAttributes:applyAttributes:isFocused:notify:] + 1992
	13  UIKitCore                           0x0000000184a46780 -[UICollectionView _createVisibleViewsForSingleCategoryAttributes:limitCreation:fadeForBoundsChange:] + 1064
	14  UIKitCore                           0x0000000184a46a9c -[UICollectionView _createVisibleViewsForAttributes:fadeForBoundsChange:notifyLayoutForVisibleCellsPass:] + 288
	15  UIKitCore                           0x0000000184a44e90 -[UICollectionView _updateVisibleCellsNow:] + 3180
	16  UIKitCore                           0x0000000184a49ec4 -[UICollectionView layoutSubviews] + 300
	17  UIKitCore                           0x0000000185806d78 -[UIView(CALayerDelegate) layoutSublayersOfLayer:] + 1492
	18  QuartzCore                          0x0000000189ffa5b0 _ZN2CA5Layer16layout_if_neededEPNS_11TransactionE + 440
	19  QuartzCore                          0x000000018a005368 _ZN2CA5Layer28layout_and_display_if_neededEPNS_11TransactionE + 124
	20  QuartzCore                          0x0000000189f20520 _ZN2CA7Context18commit_transactionEPNS_11TransactionEdPd + 460
	21  QuartzCore                          0x0000000189f4fcc0 _ZN2CA11Transaction6commitEv + 652
	22  UIKitCore                           0x0000000185308804 __34-[UIApplication _firstCommitBlock]_block_invoke_2 + 32
	23  CoreFoundation                      0x00000001803f1ce0 __CFRUNLOOP_IS_CALLING_OUT_TO_A_BLOCK__ + 20
	24  CoreFoundation                      0x00000001803f1428 __CFRunLoopDoBlocks + 352
	25  CoreFoundation                      0x00000001803ebccc __CFRunLoopRun + 788
	26  CoreFoundation                      0x00000001803eb5a4 CFRunLoopRunSpecific + 572
	27  GraphicsServices                    0x000000018e9fbae4 GSEventRunModal + 160
	28  UIKitCore                           0x00000001852f02e4 -[UIApplication _run] + 868
	29  UIKitCore                           0x00000001852f3f5c UIApplicationMain + 124
	30  libxamarin-dotnet-debug.dylib       0x000000010245bf44 xamarin_UIApplicationMain + 60
	31  libmonosgen-2.0.dylib               0x0000000102b8ca50 do_icall + 316
	32  libmonosgen-2.0.dylib               0x0000000102b8b2f0 do_icall_wrapper + 356
	33  libmonosgen-2.0.dylib               0x0000000102b7fd3c mono_interp_exec_method + 2784
	34  libmonosgen-2.0.dylib               0x0000000102b7d910 interp_runtime_invoke + 244
	35  libmonosgen-2.0.dylib               0x0000000102a969b0 mono_jit_runtime_invoke + 1116
	36  libmonosgen-2.0.dylib               0x0000000102c51a14 mono_runtime_invoke_checked + 148
	37  libmonosgen-2.0.dylib               0x0000000102c58ff4 mono_runtime_exec_main_checked + 116
	38  libmonosgen-2.0.dylib               0x0000000102aeac70 mono_jit_exec + 364
	39  libxamarin-dotnet-debug.dylib       0x000000010249fb00 xamarin_main + 2320
	40  MediaElementCarouselBug             0x0000000100b5ab44 main + 72
	41  dyld                                0x00000001015cd544 start_sim + 20
	42  ???                                 0x00000001010ca0e0 0x0 + 4312572128
	43  ???                                 0x5a5a000000000000 0x0 + 6510516211317473280

   at ObjCRuntime.Runtime.ThrowException(IntPtr gchandle) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/ObjCRuntime/Runtime.cs:line 2594
   at UIKit.UIApplication.UIApplicationMain(Int32 argc, String[] argv, IntPtr principalClassName, IntPtr delegateClassName) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/UIKit/UIApplication.cs:line 60
   at UIKit.UIApplication.Main(String[] args, Type principalClass, Type delegateClass) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/UIKit/UIApplication.cs:line 94
   at MediaElementCarouselBug.Program.Main(String[] args) in F:\Source\experiments\MediaElementCarouselBug\Platforms\iOS\Program.cs:line 14
Native stack trace:
	0   CoreFoundation                      0x0000000180491128 __exceptionPreprocess + 172
	1   libobjc.A.dylib                     0x000000018008412c objc_exception_throw + 56
	2   CoreFoundation                      0x0000000180491038 -[NSException initWithCoder:] + 0
	3   UIKitCore                           0x00000001857f3ae4 -[UIView(Hierarchy) _associatedViewControllerForwardsAppearanceCallbacks:performHierarchyCheck:isRoot:] + 216
	4   UIKitCore                           0x00000001857f4250 -[UIView(Hierarchy) _willMoveToWindow:withAncestorView:] + 184
	5   UIKitCore                           0x00000001857f4d18 _makeSubTreePerformSelector + 428
	6   UIKitCore                           0x00000001857f4d54 _makeSubTreePerformSelector + 488
	7   UIKitCore                           0x00000001857f4d54 _makeSubTreePerformSelector + 488
	8   UIKitCore                           0x00000001858016a0 -[UIView(Internal) _addSubview:positioned:relativeTo:] + 384
	9   UIKitCore                           0x0000000184a39e3c -[UICollectionView _addSubview:positioned:relativeTo:] + 144
	10  UIKitCore                           0x00000001854bc098 -[_UICollectionViewSubviewRouter addControlledSubview:zIndex:orderMode:] + 816
	11  UIKitCore                           0x0000000184a39a34 -[UICollectionView _addControlledSubview:atZIndex:forced:initialAttributes:] + 300
	12  UIKitCore                           0x0000000184a3e038 -[UICollectionView _createPreparedCellForItemAtIndexPath:withLayoutAttributes:applyAttributes:isFocused:notify:] + 1992
	13  UIKitCore                           0x0000000184a46780 -[UICollectionView _createVisibleViewsForSingleCategoryAttributes:limitCreation:fadeForBoundsChange:] + 1064
	14  UIKitCore                           0x0000000184a46a9c -[UICollectionView _createVisibleViewsForAttributes:fadeForBoundsChange:notifyLayoutForVisibleCellsPass:] + 288
	15  UIKitCore                           0x0000000184a44e90 -[UICollectionView _updateVisibleCellsNow:] + 3180
	16  UIKitCore                           0x0000000184a49ec4 -[UICollectionView layoutSubviews] + 300
	17  UIKitCore                           0x0000000185806d78 -[UIView(CALayerDelegate) layoutSublayersOfLayer:] + 1492
	18  QuartzCore                          0x0000000189ffa5b0 _ZN2CA5Layer16layout_if_neededEPNS_11TransactionE + 440
	19  QuartzCore                          0x000000018a005368 _ZN2CA5Layer28layout_and_display_if_neededEPNS_11TransactionE + 124
	20  QuartzCore                          0x0000000189f20520 _ZN2CA7Context18commit_transactionEPNS_11TransactionEdPd + 460
	21  QuartzCore                          0x0000000189f4fcc0 _ZN2CA11Transaction6commitEv + 652
	22  UIKitCore                           0x0000000185308804 __34-[UIApplication _firstCommitBlock]_block_invoke_2 + 32
	23  CoreFoundation                      0x00000001803f1ce0 __CFRUNLOOP_IS_CALLING_OUT_TO_A_BLOCK__ + 20
	24  CoreFoundation                      0x00000001803f1428 __CFRunLoopDoBlocks + 352
	25  CoreFoundation                      0x00000001803ebccc __CFRunLoopRun + 788
	26  CoreFoundation                      0x00000001803eb5a4 CFRunLoopRunSpecific + 572
	27  GraphicsServices                    0x000000018e9fbae4 GSEventRunModal + 160
	28  UIKitCore                           0x00000001852f02e4 -[UIApplication _run] + 868
	29  UIKitCore                           0x00000001852f3f5c UIApplicationMain + 124
	30  libxamarin-dotnet-debug.dylib       0x000000010245bf44 xamarin_UIApplicationMain + 60
	31  libmonosgen-2.0.dylib               0x0000000102b8ca50 do_icall + 316
	32  libmonosgen-2.0.dylib               0x0000000102b8b2f0 do_icall_wrapper + 356
	33  libmonosgen-2.0.dylib               0x0000000102b7fd3c mono_interp_exec_method + 2784
	34  libmonosgen-2.0.dylib               0x0000000102b7d910 interp_runtime_invoke + 244
	35  libmonosgen-2.0.dylib               0x0000000102a969b0 mono_jit_runtime_invoke + 1116
	36  libmonosgen-2.0.dylib               0x0000000102c51a14 mono_runtime_invoke_checked + 148
	37  libmonosgen-2.0.dylib               0x0000000102c58ff4 mono_runtime_exec_main_checked + 116
	38  libmonosgen-2.0.dylib               0x0000000102aeac70 mono_jit_exec + 364
	39  libxamarin-dotnet-debug.dylib       0x000000010249fb00 xamarin_main + 2320
	40  MediaElementCarouselBug             0x0000000100b5ab44 main + 72
	41  dyld                                0x00000001015cd544 start_sim + 20
	42  ???                                 0x00000001010ca0e0 0x0 + 4312572128
	43  ???                                 0x5a5a000000000000 0x0 + 6510516211317473280
2024-02-29 10:20:42.258618+0000 MediaElementCarouselBug[5811:1634581] Unhandled managed exception: Objective-C exception thrown.  Name: UIViewControllerHierarchyInconsistency Reason: child view controller:<AVPlayerViewController: 0x104008800> should have parent view controller:<Microsoft_Maui_Controls_Handlers_Items_CarouselViewController: 0x102777b80> but actual parent is:<Microsoft_Maui_Platform_PageViewController: 0x102774910>
Native stack trace:
	0   CoreFoundation                      0x0000000180491128 __exceptionPreprocess + 172
	1   libobjc.A.dylib                     0x000000018008412c objc_exception_throw + 56
	2   CoreFoundation                      0x0000000180491038 -[NSException initWithCoder:] + 0
	3   UIKitCore                           0x00000001857f3ae4 -[UIView(Hierarchy) _associatedViewControllerForwardsAppearanceCallbacks:performHierarchyCheck:isRoot:] + 216
	4   UIKitCore                           0x00000001857f4250 -[UIView(Hierarchy) _willMoveToWindow:withAncestorView:] + 184
	5   UIKitCore                           0x00000001857f4d18 _makeSubTreePerformSelector + 428
	6   UIKitCore                           0x00000001857f4d54 _makeSubTreePerformSelector + 488
	7   UIKitCore                           0x00000001857f4d54 _makeSubTreePerformSelector + 488
	8   UIKitCore                           0x00000001858016a0 -[UIView(Internal) _addSubview:positioned:relativeTo:] + 384
	9   UIKitCore                           0x0000000184a39e3c -[UICollectionView _addSubview:positioned:relativeTo:] + 144
	10  UIKitCore                           0x00000001854bc098 -[_UICollectionViewSubviewRouter addControlledSubview:zIndex:orderMode:] + 816
	11  UIKitCore                           0x0000000184a39a34 -[UICollectionView _addControlledSubview:atZIndex:forced:initialAttributes:] + 300
	12  UIKitCore                           0x0000000184a3e038 -[UICollectionView _createPreparedCellForItemAtIndexPath:withLayoutAttributes:applyAttributes:isFocused:notify:] + 1992
	13  UIKitCore                           0x0000000184a46780 -[UICollectionView _createVisibleViewsForSingleCategoryAttributes:limitCreation:fadeForBoundsChange:] + 1064
	14  UIKitCore                           0x0000000184a46a9c -[UICollectionView _createVisibleViewsForAttributes:fadeForBoundsChange:notifyLayoutForVisibleCellsPass:] + 288
	15  UIKitCore                           0x0000000184a44e90 -[UICollectionView _updateVisibleCellsNow:] + 3180
	16  UIKitCore                           0x0000000184a49ec4 -[UICollectionView layoutSubviews] + 300
	17  UIKitCore                           0x0000000185806d78 -[UIView(CALayerDelegate) layoutSublayersOfLayer:] + 1492
	18  QuartzCore                          0x0000000189ffa5b0 _ZN2CA5Layer16layout_if_neededEPNS_11TransactionE + 440
	19  QuartzCore                          0x000000018a005368 _ZN2CA5Layer28layout_and_display_if_neededEPNS_11TransactionE + 124
	20  QuartzCore                          0x0000000189f20520 _ZN2CA7Context18commit_transactionEPNS_11TransactionEdPd + 460
	21  QuartzCore                          0x0000000189f4fcc0 _ZN2CA11Transaction6commitEv + 652
	22  UIKitCore                           0x0000000185308804 __34-[UIApplication _firstCommitBlock]_block_invoke_2 + 32
	23  CoreFoundation                      0x00000001803f1ce0 __CFRUNLOOP_IS_CALLING_OUT_TO_A_BLOCK__ + 20
	24  CoreFoundation                      0x00000001803f1428 __CFRunLoopDoBlocks + 352
	25  CoreFoundation                      0x00000001803ebccc __CFRunLoopRun + 788
	26  CoreFoundation                      0x00000001803eb5a4 CFRunLoopRunSpecific + 572
	27  GraphicsServices                    0x000000018e9fbae4 GSEventRunModal + 160
	28  UIKitCore                           0x00000001852f02e4 -[UIApplication _run] + 868
	29  UIKitCore                           0x00000001852f3f5c UIApplicationMain + 124
	30  libxamarin-dotnet-debug.dylib       0x000000010245bf44 xamarin_UIApplicationMain + 60
	31  libmonosgen-2.0.dylib               0x0000000102b8ca50 do_icall + 316
	32  libmonosgen-2.0.dylib               0x0000000102b8b2f0 do_icall_wrapper + 356
	33  libmonosgen-2.0.dylib               0x0000000102b7fd3c mono_interp_exec_method + 2784
	34  libmonosgen-2.0.dylib               0x0000000102b7d910 interp_runtime_invoke + 244
	35  libmonosgen-2.0.dylib               0x0000000102a969b0 mono_jit_runtime_invoke + 1116
	36  libmonosgen-2.0.dylib               0x0000000102c51a14 mono_runtime_invoke_checked + 148
	37  libmonosgen-2.0.dylib               0x0000000102c58ff4 mono_runtime_exec_main_checked + 116
	38  libmonosgen-2.0.dylib               0x0000000102aeac70 mono_jit_exec + 364
	39  libxamarin-dotnet-debug.dylib       0x000000010249fb00 xamarin_main + 2320
	40  MediaElementCarouselBug             0x0000000100b5ab44 main + 72
	41  dyld                                0x00000001015cd544 start_sim + 20
	42  ???                                 0x00000001010ca0e0 0x0 + 4312572128
	43  ???                                 0x5a5a000000000000 0x0 + 6510516211317473280
 (ObjCRuntime.ObjCException)
   at ObjCRuntime.Runtime.ThrowException(IntPtr gchandle) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/ObjCRuntime/Runtime.cs:line 2594
   at UIKit.UIApplication.UIApplicationMain(Int32 argc, String[] argv, IntPtr principalClassName, IntPtr delegateClassName) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/UIKit/UIApplication.cs:line 60
   at UIKit.UIApplication.Main(String[] args, Type principalClass, Type delegateClass) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/UIKit/UIApplication.cs:line 94
   at MediaElementCarouselBug.Program.Main(String[] args) in F:\Source\experiments\MediaElementCarouselBug\Platforms\iOS\Program.cs:line 14

=================================================================
	Native Crash Reporting
=================================================================
Got a SIGABRT while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.
=================================================================

=============================
====================================
	Native stacktrace:
=================================================================
	0x102b7c1a0 - /Users/onewizard/Library/Developer/CoreSimulator/Devices/6032833E-9302-4B57-9D8E-460CBD3073E5/data/Containers/Bundle/Application/6841077E-2E44-437A-9E43-2CC53F2465BE/MediaElementCarouselBug.app/libmonosgen-2.0.dylib : mono_dump_native_crash_info
	0x102b2c1c0 - /Users/onewizard/Library/Developer/CoreSimulator/Devices/6032833E-9302-4B57-9D8E-460CBD3073E5/data/Containers/Bundle/Application/6841077E-2E44-437A-9E43-2CC53F2465BE/MediaElementCarouselBug.app/libmonosgen-2.0.dylib : mono_handle_native_crash
	0x102e4ebc8 - /Users/onewizard/Library/Developer/CoreSimulator/Devices/6032833E-9302-4B57-9D8E-460CBD3073E5/data/Containers/Bundle/Application/6841077E-2E44-437A-9E43-2CC53F2465BE/MediaElementCarouselBug.app/libmonosgen-2.0.dylib : sigabrt_signal_handler.cold.1
	0x102b7ba60 - /Users/onewizard/Library/Developer/CoreSimulator/Devices/6032833E-9302-4B57-9D8E-460CBD3073E5/data/Containers/Bundle/Application/6841077E-2E44-437A-9E43-2CC53F2465BE/MediaElementCarouselBug.app/libmonosgen-2.0.dylib : mono_runtime_setup_stat_profiler
	0x100ffbc60 - /usr/lib/system/libsystem_platform.dylib : _sigtramp
	0x101edb1d0 - /usr/lib/system/libsystem_pthread.dylib : pthread_kill
	0x1801605cc - /Library/Developer/CoreSimulator/Volumes/iOS_21C62/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.2.simruntime/Contents/Resources/RuntimeRoot/usr/lib/system/libsystem_c.dylib : abort
	0x10248b098 - /Users/onewizard/Library/Developer/CoreSimulator/Devices/6032833E-9302-4B57-9D8E-460CBD3073E5/data/Containers/Bundle/Application/6841077E-2E44-437A-9E43-2CC53F2465BE/MediaElementCarouselBug.app/libxamarin-dotnet-debug.dylib : xamarin_find_protocol_wrapper_type
	0x102c09150 - /Users/onewizard/Library/Developer/CoreSimulator/Devices/6032833E-9302-4B57-9D8E-460CBD3073E5/data/Containers/Bundle/Application/6841077E-2E44-437A-9E43-2CC53F2465BE/MediaElementCarouselBug.app/libmonosgen-2.0.dylib : mono_invoke_unhandled_exception_hook
	0x102aeac98 - /Users/onewizard/Library/Developer/CoreSimulator/Devices/6032833E-9302-4B57-9D8E-460CBD3073E5/data/Containers/Bundle/Application/6841077E-2E44-437A-9E43-2CC53F2465BE/MediaElementCarouselBug.app/libmonosgen-2.0.dylib : mono_jit_exec
	0x10249fb00 - /Users/onewizard/Library/Developer/CoreSimulator/Devices/6032833E-9302-4B57-9D8E-460CBD3073E5/data/Containers/Bundle/Application/6841077E-2E44-437A-9E43-2CC53F2465BE/MediaElementCarouselBug.app/libxamarin-dotnet-debug.dylib : xamarin_main
	0x100b5ab44 - /Users/onewizard/Library/Developer/CoreSimulator/Devices/6032833E-9302-4B57-9D8E-460CBD3073E5/data/Containers/Bundle/Application/6841077E-2E44-437A-9E43-2CC53F2465BE/MediaElementCarouselBug.app/MediaElementCarouselBug : main
	0x1015cd544 - Unknown
	0x1010ca0e0 - Unknown
	0x5a5a000000000000 - Unknown

=================================================================
	Basic Fault Address Reporting
=================================================================
Memory around native instruction pointer (0x1020889ec):0x1020889dc  c0 03 5f d6 c0 03 5f d6 10 29 80 d2 
01 10 00 d4  .._..._..)......
0x1020889ec  e3 00 00 54 fd 7b bf a9 fd 03 
00 91 ce e2 ff 97  ...T.{..........
0x1020889fc  bf 03 00 91 fd 7b c1 
a8 c0 03 5f d6 c0 03 5f d6  .....{...._..._.
0x102088a0c  
70 0a 80 d2 01 10 00 d4 e3 00 00 54 fd 7b bf a9  p........
..T.{..

=================================================================
	Managed Stacktrace:
=================================================================
=================================================================
```

### Expected Behavior

The app should not crash

### Steps To Reproduce

1. Create a .NET MAUI app
2. Add a page with a CarouselView with a MediaElement in the ItemTemplate
3. Add one or more sources to the ItemsSource of the CarouselView
4. Run the app on iOS and open the page

### Link to public reproduction project repository

https://github.com/dan3988/MediaElementCarouselBug

### Environment

```markdown
- CommunityToolkit.Maui.MediaElement: 3.0.1
- OS: iOS 17.2
- .NET MAUI: 8.0
```

**Comment by vhugogarcia** [comment]
Thanks @dan3988 , this issue has been fixed on the following PR: https://github.com/CommunityToolkit/Maui/pull/1597 , we expect this fix to be released on the next version of the Community Toolkit.

Regards,
Victor

**Comment by dan3988** [comment]
Hi, @vhugogarcia, I've updated the reproduction repository to use version 3.1.1 and the issue is still present. Please can this be re-opened?
