### ISSUE TITLE
[BUG] StatusBarColor not applied with .NET 10 RC using StatusBarBehavior

### ISSUE THREAD

**Issue by lennard393** [CommunityToolkit/Maui#2936]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [x] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

When setting the status bar colour using StatusBarBehavior or the Platform.StatusBar API in .NET 10 Release Candidate, the colour and style are not applied as expected. The same code works correctly in previous versions (e.g., .NET 9).

### Expected Behavior

The Colour and style should be applied

### Steps To Reproduce

Create a new .NET 10 RC MAUI project.

Install the latest CommunityToolkit.Maui package (12.3.0)

Add the following XAML to a page:

  <ContentPage.Behaviors>
    <toolkit:StatusBarBehavior 
        StatusBarColor="Red"
        StatusBarStyle="LightContent"/>
  </ContentPage.Behaviors>

### Link to public reproduction project repository

https://github.com/lennard393/CommunityToolkit.StatusbarColor-Bug/tree/master/CommunityToolkit.StatusbarColor

### Environment

```markdown
- .NET MAUI CommunityToolkit: 12.3.0
- OS: Windows 10 Build 10.0.19041.0
- .NET MAUI: 10
```

**Comment by ne0rrmatrix** [comment]
Hopefully this fixes the issue. https://github.com/dotnet/maui/pull/32015 It was merged 2 days ago. They provided a link with a way to test with the PR and if it solves your issue please report back.

**Comment by mfeingol** [comment]
I just updated to Maui 10.0.10 which has this fix, and ... it doesn't work. 

Calling `CommunityToolkit.Maui.Core.Platform.StatusBar.SetColor(statusBarColor);` no longer changes the default status bar color with .NET 10 and Android API Level 36. Your code calls `SetBackgroundColor` on the DecorView, but that doesn't appear to do anything. It looks like a new Android.Views.View must be created with a background color, and then added to the DecorView as a ViewGroup.

**Comment by tranb3r** [comment]
Any workaround?

**Comment by pictos** [comment]
I believe the MCT isn't full compatible with .net 10, but as workaround, can you try this and see if it works?
https://learn.microsoft.com/en-us/dotnet/communitytoolkit/maui/platform-specific/dialogfragment-customization

**Comment by mfeingol** [comment]
> Any workaround?

Something along these lines for now:

```c#
static void SetStatusBarColor()
{
    Color statusBarColor = Colors.Red; // TODO: get appropriate color for your situation

    if (Build.VERSION.SdkInt < BuildVersionCodes.VanillaIceCream)
    {
        CommunityToolkit.Maui.Core.Platform.StatusBar.SetColor(statusBarColor);
    }
    else
    {
        Android.App.Activity activity = Microsoft.Maui.ApplicationModel.Platform.CurrentActivity;
        Android.Views.Window window = activity?.Window;
        if (window != null)
        {
            const string StatusBarOverlayTag = "StatusBarOverlay";

            Android.Views.ViewGroup decorGroup = (Android.Views.ViewGroup)window.DecorView;
            Android.Views.View statusBarOverlay = decorGroup.FindViewWithTag(StatusBarOverlayTag);
            if (statusBarOverlay == null)
            {
                int statusBarHeight = activity.Resources.GetIdentifier("status_bar_height", "dimen", "android");
                int height = statusBarHeight > 0 ? activity.Resources.GetDimensionPixelSize(statusBarHeight) : 0;

                statusBarOverlay = new(activity)
                {
                    LayoutParameters = new Android.Widget.FrameLayout.LayoutParams(Android.Views.ViewGroup.LayoutParams.MatchParent, height + 3) { Gravity = Android.Views.GravityFlags.Top }
                };

                decorGroup.AddView(statusBarOverlay);
                statusBarOverlay.SetZ(0);
            }
            statusBarOverlay.SetBackgroundColor(statusBarColor.ToAndroid());

            WindowInsetsControllerCompat controller = WindowCompat.GetInsetsController(window, decorGroup);
            controller.AppearanceLightStatusBars = useLightIcons; // TODO: depends on your color
        }
    }
}
```

**Comment by mfeingol** [comment]
> I believe the MCT isn't full compatible with .net 10, but as workaround, can you try this and see if it works? https://learn.microsoft.com/en-us/dotnet/communitytoolkit/maui/platform-specific/dialogfragment-customization

Not sure I follow how this relates to the status bar color?

**Comment by pictos** [comment]
@mfeingol did you read the docs? It's on the first section (:

**Comment by TheCodeTraveler** [comment]
This is fixed in our .NET 10 PR and will be included in our next release, `CommunityToolkit.Maui v13.0.0`: https://github.com/CommunityToolkit/Maui/pull/2902/files#diff-977ed6ea59fb638d6ad2b223434fdc48a86ed77cee069bb85cd4554c47b08401R42-R50

@jfversluis is the only member of the team who has the permissions to publish our releases. I pinged him yesterday to publish the new releases.

**Comment by mfeingol** [comment]
@TheCodeTraveler: I picked up 13.0.0 and calling `CommunityToolkit.Maui.Core.Platform.StatusBar.SetColor(statusBarColor);` still does not work on Android 16.

This code is not sufficient to set the color of the status bar: https://github.com/CommunityToolkit/Maui/blob/main/src/CommunityToolkit.Maui.Core/Platform/StatusBar/StatusBar.android.cs#L45

Please see my sample code above for what I had to do inside my app.

**Comment by TheCodeTraveler** [comment]
Is the error only happening on Android API 16?

We only support Android API 21 and higher:
https://learn.microsoft.com/en-us/dotnet/communitytoolkit/maui/#supported-versions

<img width="541" height="283" alt="Image" src="https://github.com/user-attachments/assets/a449f14d-7bea-41aa-9830-edbd3e30d63c" />

**Comment by mfeingol** [comment]
I meant Android 16 => API level 36.

**Comment by TheCodeTraveler** [comment]
Got it! Thanks for the info and thanks for the fix @mfeingol! 

PR Submitted: https://github.com/CommunityToolkit/Maui/pull/2939

**Comment by lennard393** [comment]
Just to clarify: the status bar color is not changing on API 30 either, so this issue isn’t limited to API 35+.

Thanks for looking into it, @TheCodeTraveler
