### ISSUE TITLE
[BUG] Popup - Size is not respected in Landscape mode on iOS

### ISSUE THREAD

**Issue by Eltee-Taiwo** [CommunityToolkit/Maui#843]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The Size property of a Popup is not respected when using an iOS device in Landscape mode and popups always take up the full size of the screen.

### Expected Behavior

The Size property should be respected and popups should be sizeable rather than full screen when using iOS in Landscape mode.

### Steps To Reproduce

1. Open and run solution
2. Click button to display popup
3. Notice size is respected.
4. Close Popup
5. Switch to landscape mode
6. Click button to display popup
7. Popup uses full screen

### Link to public reproduction project repository

https://github.com/jfversluis/MauiToolkitPopupSample

### Environment

```markdown
- .NET MAUI CommunityToolkit: 1.3.0
- OS: Windows 10 + Ventura 13 (M1)
- .NET MAUI: 6
```

### Anything else?

![image](https://user-images.githubusercontent.com/37124491/209448937-5d7ae888-704b-469f-b3eb-e36e81f251f3.png)
![image](https://user-images.githubusercontent.com/37124491/209448938-9f78099a-35bd-42e0-944b-2497bbc26e59.png)

**Comment by brminnick** [comment]
Fixed in https://github.com/CommunityToolkit/Maui/pull/1320

**Comment by VNGames** [comment]
@brminnick It isn't fixed.
Opened a new bug
https://github.com/CommunityToolkit/Maui/issues/1604

**Comment by jfversluis** [comment]
Seems that this wasn't fixed yet, let's reopen to have another look

**Comment by vhugogarcia** [comment]
This issue has been fixed. I tested it using the latest version. Please find attached screenshots of the popup maintaining the position when rotate the device. For the reason mentioned previously, I'm closing this issue.


![Simulator Screenshot - iPhone 15 - 2024-06-21 at 10 42 12](https://github.com/CommunityToolkit/Maui/assets/1047398/987e75e5-ce4d-4637-8f6b-9e296a3763ac)
![Simulator Screenshot - iPhone 15 - 2024-06-21 at 10 42 07](https://github.com/CommunityToolkit/Maui/assets/1047398/0c671ae6-7afb-42e3-98c5-0a8dd76bca40)
![Simulator Screenshot - iPhone 15 - 2024-06-21 at 10 41 57](https://github.com/CommunityToolkit/Maui/assets/1047398/6cd2aa6f-aa9f-4d2b-b189-2ccf42d6f3b3)
![Simulator Screenshot - iPhone 15 - 2024-06-21 at 10 41 48](https://github.com/CommunityToolkit/Maui/assets/1047398/a5c89e7c-ac81-48dd-8391-be529fe1d635)
![Simulator Screenshot - iPhone 15 - 2024-06-21 at 10 41 10](https://github.com/CommunityToolkit/Maui/assets/1047398/92d8d7ac-5f06-4e54-a9a6-b787dd3490f2)
![Simulator Screenshot - iPhone 15 - 2024-06-21 at 10 41 04](https://github.com/CommunityToolkit/Maui/assets/1047398/9902f6b6-9b72-4e30-82b9-3fbd9cd716f7)
